config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  resources :books
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, {length: {maximum:200} }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2,maximum: 20 }
  validates :introduction, length: {maximum:50} 

  def get_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     flash[:notice] = 'Signed in successfully.'
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
     flash[:notice] = 'Welcome! You have signed up successfully.'
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = 'Signed out successfully.'
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:top]
   before_action :configure_permitted_parameters, if: :devise_controller?
  def new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
   redirect_to book_path(@book.id)
   flash[:notice] =  'You have created book successfully.'
   else
     render :index
   end
  end
  
  def update
  user_id = Book.find(params[:id]).user.id.to_i
  login_user_id = current_user.id
  if(user_id != login_user_id)
    redirect_to books_path
  end 
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :edit
     
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
 
  def show
     @book = Book.find(params[:id])
     @user = @book.user
  end

  def edit
  user_id = Book.find(params[:id]).user.id.to_i
  login_user_id = current_user.id
  if(user_id != login_user_id)
    redirect_to books_path
  end 
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end
  
   private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def new
  end

  def edit
    @user = User.find(params[:id])
    user_id = params[:id].to_i
  login_user_id = current_user.id
  if(user_id != login_user_id)
    redirect_to user_path(current_user.id)
  end

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
  end

  def update
    user_id = params[:id].to_i
  login_user_id = current_user.id
  if(user_id != login_user_id)
    redirect_to books_path
  end
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
    @users = User.all
    render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
 <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="mt-3">
  <h2>User info</h2>
 <%= image_tag current_user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
   <div> <i class="fa-solid fa-user-gear"></i>
      <%= link_to "Edit", edit_user_path(current_user) %>
     </div>
  
<h2>New book</h2>
<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit 'Create Book' %></div>
        <% end %>
    </div>
    </div>
    </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
<h2>User info</h2>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      
      
        <%= form_with model: @book do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_field :body %></br></div>
        <div class="form-group">
        <%= f.submit 'Update Book' %></div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>|
        <a href="/books">Back</a>
      </div>
      
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= flash[:notice] %>

  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag current_user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></li></th>
      </tr>
    </tbody>
  </table>

    <%= link_to edit_user_path(current_user.id) do %>
    <div class="row"><div class="btn btn-outline-secondary btn-block" >
      <i class="fas fa-user-cog"></i></div>
     </div><% end %>


<h2>New book</h2>

<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %></div>
        <% end %>
  </div>

<div class="col-md-8 offset-md-1">

    <h2>Books</h2>
<table class ="table table-hover table-inverse">
    <thread>
        <tr>
        <th></th>
        <th>Title</th>

        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
    </thread>
    <% Book.all.each do |book| %>
    <tbody>
    <tr>
      <td><%= link_to user_path(book.user) do %>
      <%= image_tag book.user.get_image(100,100) %> <% end %>
          </td>
      <td><%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %></td>
      <td><%= book.body %></td>

     </tr>

    </tbody><% end %>
</table>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @book.user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @book.user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= @book.user.introduction %></th>
      </tr>
    </tbody>
  </table>




    <%= link_to edit_user_path(@user.id) do %>
    <div class="row"><div class="btn btn-outline-secondary btn-block" >
      <i class="fas fa-user-cog"></i></div>
     </div><% end %>

<h2 class="mt-3">New book</h2>

<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %></div>
        <% end %>
  </div>

  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
<table class="table">
  <tr>
    <td><%= link_to user_path(@book.user) do %>
      <%= image_tag @book.user.get_image(100,100) %>
      <br><%= @book.user.name %></br><% end %>
    </td>
    <td>
     <td>
      <%= link_to book_path(@book) do %>
      <%= @book.title %>
      <% end %>
    </td>
    <td>
      <%= @book.body %>
    </td>
    <td><% if @book.user == current_user %>
        <%= link_to edit_book_path(@book) do %><div class="btn btn-sm btn-success" >Edit</div><% end %><% end %>
    </td>
    <td>
      <% if @book.user == current_user %>
        <%= link_to book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" do %><div class="btn btn-sm btn-danger">Destroy</div><% end %><% end %>
    </td>
  </tr>
</table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to
<i class="fas fa-book"></i>
        <strong>Bookers</strong>!!
</h1></div></div>

app/views/homes/top.html.erb
<%= flash[:notice] %>

<main>
  
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>Welcome to <i class="fas fa-book"></i>
        <strong>Bookers</strong>!!
        </h1>
        <p>In<i class="fas fa-book"></i>
        <strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <header>
      <nav class="navbar navbar-expend-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expended="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
     <%= link_to user_path(current_user.id) do %><li class="nav-link text-light"><i class="fas fa-home"></i>Home
     </li><% end %>
     <li><a class="nav-link text-light" href="/users"><i class="fas fa-users"></i>Users</a>
     </li>
     <li>
       <a class="nav-link text-light" href="/books"><i class="fas fa-book-open"></i>Books</a>
     </li>
      <%= link_to destroy_user_session_path, method: :delete do %><li class="nav-link text-light" href=><i class="fas fa-sign-out-alt"></i>Log out
      </li><% end %>


    <% else %>
     <li><a class="nav-link text-light" href=""><i class="fas fa-home"></i>Home</a></li>
     <li><a class="nav-link text-light" href="/home/about"><i class="fas fa-link"></i>About</a>
     </li>
     <li>
       <a class="nav-link text-light" href="/users/sign_up"><i class="fas fa-user-plus"></i>Sign up</a>
     </li>
      <a class="nav-link text-light" href="users/sign_in"><i class="fas fa-sign-in-alt"></i>Log in</a>
      </li>

    <% end %>
    </ul>
    </div>
    </div>
    </nav>
  </header>
  <main>
  <%= yield %>
  </main>
  <footer>
     <i class="fa-solid fa-user-gear"></i>
    <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
      </div>
    </div>
  </footer>

  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %><h2>User info</h2>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class = "container">
  <div class = "row" >
<div class ="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name ,class: :"form-control-file user_image" %>
  </div>
  <div class="form-group">
    <label for="user_image">Image</label>
    <%= f.file_field :profile_image, accept: "image/*",class: :"form-control-file user_image" %>
  </div>
  <div class="form-group">
    <label for="user_introduction">Introduction</label>
    <%= f.text_area :introduction ,class: :"form-control-file introduction" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update User" ,class: :"btn btn-secondary" %>

  </div>
  <% end %>
</div></div></div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag current_user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <%= link_to edit_user_path(current_user.id) do %>
    <div class="row"><div class="btn btn-outline-secondary btn-block" >
      <i class="fas fa-user-cog"></i></div>
     </div><% end %>


<h2>New book</h2>

<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %></div>
        <% end %>
  </div>



<div class="col-md-8 offset-md-1">

    <h2>Users</h2>
<table class ="table table-hover table-inverse">
    <thread>
        <tr>
        <th>image</th>

        <th>name</th>
        <th colspan="3"></th>
        </tr>
    </thread>
    <% @users.each do |user| %>


    <tbody>
    <tr>
      <td><%= image_tag user.get_image(80,80) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
    </tbody><% end %>
</table>
</div>
</div>
</div>

app/views/users/new.html.erb
  <div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag current_user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= current_user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
    
    <div class="row">
    <a class="btn btn-outline-secoudary btn-block">
      <i class="fas fa-user-cog"></i></a>
      
      <%= link_to "Edit" , edit_user_path(current_user.id) %></div>
    
    
<h2>New book</h2>

<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit 'Create Book' %></div>
        <% end %>
  </div>

<div class="col-md-8 offset-md-1">
    
    <h2>Books</h2>
<table class ="table table-hover table-inverse">
    <thread>
        <tr>
        <th></th>
        <th>Title</th>
        
        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
    </thread>
    <% Book.all.each do |book| %>
    <tbody>
    <tr>
      <td><%= link_to user_path(book.user) do %>
      <%= image_tag book.user.get_image(100,100) %> <% end %>
          </td>
      <td><%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %></td>
      <td><%= book.body %></td>
     
      <td> <% if book.user == current_user %><%= link_to "Edit", edit_book_path(book.id) %><% end %></td>
  <td><% if book.user == current_user %><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure ?" %><% end %></td>
    </tr>
    
    </tbody><% end %>
</table>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @user.get_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
      <th>name</th>
      <th><%= @user.name %></th>
      </tr>
      <tr>
      <th>introduction</th>
      <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>

   <%= link_to edit_user_path(@user.id) do %>
    <div class="row"><div class="btn btn-outline-secondary btn-block" >
      <i class="fas fa-user-cog"></i></div>
     </div><% end %>

<h2>New book</h2>

<%= form_with model: Book.new, method: :post do |f| %>
        <div class="form-group">
        <label for="book_title">Title</label>
        <br><%= f.text_field :title %></br></div>
        <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <br><%= f.text_area :body %></br></div>
        <div class="form-group">
        <%= f.submit "Create Book", class: :"btn btn-success" %></div>
        <% end %>
  </div>

<div class="col-md-8 offset-md-1">

  <h2>Books</h2>

  <table class="table table-hover table-inverse">
    <thread>
        <tr>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
        </tr>
    </thread>
    <% @books.each do |book| %>
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= image_tag @user.get_image(100,100)%>
          <% end %>
          </td>
        <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  </div>
  </div>
  </div>